---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.5
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    hubble:
      enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: traefik-internal
          hosts:
            - hubble.${clusterDomain}
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: networking-internal-oauth@kubernetescrd
      relay:
        enabled: true
        rollOutPods: true
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: ["10.24.0.0/16"]
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 10.24.0.0/16
    routingMode: native
    bpf:
      masquerade: true
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6444
    operator:
      rollOutPods: true
    rollOutCiliumPods: true
    l2announcements:
      enabled: true
    loadBalancer:
      algorithm: maglev
      mode: dsr
