---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: minio-secret
    template:
      engineVersion: v2
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: minio
        property: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: minio
        property: MINIO_ROOT_PASSWORD
