---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app minio
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  path: ./clusters/hutao/apps/default/minio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
