---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager-substitution
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/hutao/apps/networking/cert-manager/substitution
  prune: true
  dependsOn:
    - name: external-secrets-stores
  sourceRef:
    kind: GitRepository
    name: homelab-gitops
  wait: true
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/hutao/apps/networking/cert-manager/app
  prune: true
  dependsOn:
    - name: cert-manager-substitution
  sourceRef:
    kind: GitRepository
    name: homelab-gitops
  wait: true
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager-issuers
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
    - name: external-secrets-stores
  path: ./clusters/hutao/apps/networking/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops
  wait: true
  interval: 30m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cert-manager-secret
      - kind: Secret
        name: cluster-secrets
