---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 33.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    deployment:
      kind: Deployment
      replicas: 2
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik-external
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - websecure
        matchRule: Host(`traefik-external.${CLUSTER_DOMAIN}`)
        middlewares:
          - name: external-oauth
            namespace: networking
        tls:
          secretName: cluster-domain-tls
    logs:
      access:
        enabled: false
      general:
        level: DEBUG
    ports:
      web:
        expose:
          default: false
          internal: false
        exposedPort: 80
        port: 80
        protocol: TCP
        redirectTo:
          port: websecure
      websecure:
        expose:
          default: true
          internal: false
        exposedPort: 443
        http3:
          enabled: true
        middlewares: []
        port: 443
        protocol: TCP
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowEmptyServices: true
        allowExternalNameServices: true
        enabled: true
        ingressClass: traefik-external
      kubernetesIngress:
        allowEmptyServices: true
        allowExternalNameServices: true
        enabled: true
        ingressClass: traefik-external
        publishedService:
          enabled: true
    rbac:
      enabled: true
      namespaced: false
    service:
      enabled: true
      single: true
      spec:
        externalTrafficPolicy: Cluster
      type: LoadBalancer
