---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-domain-tls
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  target:
    name: cluster-domain-tls-temp
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: kubernetes.io/tls
      metadata:
        annotations:
          cert-manager.io/alt-names: "*.${clusterDomain},${clusterDomain}"
          cert-manager.io/certificate-name: cluster-domain-tls
          cert-manager.io/common-name: ${clusterDomain}
          cert-manager.io/ip-sans: ""
          cert-manager.io/issuer-group: ""
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/issuer-name: letsencrypt-staging
          cert-manager.io/uri-sans: ""
        labels:
          controller.cert-manager.io/fao: "true"
  dataFrom:
    - find:
        path: cert-manager/certificates/cluster-domain
        name:
          regexp: .*
