---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 2m
  chart:
    spec:
      chart: longhorn
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
      reclaimPolicy: Delete
      migratable: false

    preUpgradeChecker:
      jobEnabled: false
      upgradeVersionCheck: true

    defaultSettings:
      allowRecurringJobWhileVolumeDetached: false
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      replicaAutoBalance: best-effort
      storageMinimalAvailablePercentage: 10
      storageReservedPercentageForDefaultDisk: 0
      upgradeChecker: false
      defaultReplicaCount: 2
      backupstorePollInterval: 0
      failedBackupTTL: 1440
      restoreVolumeRecurringJobs: false
      recurringSuccessfulJobsHistoryLimit: 1
      recurringFailedJobsHistoryLimit: 1
      supportBundleFailedHistoryLimit: 1
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      replicaZoneSoftAntiAffinity: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      nodeDrainPolicy: block-if-contains-last-replica
      replicaReplenishmentWaitInterval: 90
      concurrentReplicaRebuildPerNodeLimit: 10
      concurrentVolumeBackupRestorePerNodeLimit: 5
      allowVolumeCreationWithDegradedAvailability: true
      autoCleanupSystemGeneratedSnapshot: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      backingImageCleanupWaitInterval: 60
      backingImageRecoveryWaitInterval: 300
      orphanAutoDeletion: true
      snapshotDataIntegrity: fast-check
      snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: false
      snapshotDataIntegrityCronjob: "0 8 */7 * *"
      removeSnapshotsDuringFilesystemTrim: false
      fastReplicaRebuildEnabled: true
      replicaFileSyncHttpClientTimeout: 30
      logLevel: Info
      backupCompressionMethod: lz4
      backupConcurrentLimit: 2
      restoreConcurrentLimit: 2
      offlineReplicaRebuilding: enabled
      allowCollectingLonghornUsageMetrics: false
