---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-gitops
  namespace: flux-system
spec:
  interval: 45s
  url: "https://github.com/6ixfalls/homelab-gitops.git"
  ref:
    branch: "main"
  ignore: |
    # exclude all
    /*
    # include clusters directory
    !/clusters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/hutao/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: homelab-gitops
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
