---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-target
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: longhorn-backup-target
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: .*