---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/hutao/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  patches:
    - patch: |-
        - op: add
          path: /spec/maxHistory
          value: 2
        - op: add
          path: /spec/install
          value:
            remediation:
              retries: 3
        - op: add
          path: /spec/upgrade
          value:
            cleanupOnFail: true
        - op: add
          path: /spec/upgrade
          value:
            remediation:
              retries: 3
        - op: add
          path: /spec/uninstall
          value:
            keepHistory: false
      target:
        kind: HelmRelease
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - kind: Secret
                name: cluster-secrets
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
