---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cilium/ks.yaml
  - ./external-secrets/ks.yaml
  - ./node-feature-discovery/ks.yaml
